apiVersion: v1
kind: Service
metadata:
  name: n8n
  labels:
    app: n8n
spec:
  type: {{ .Values.service.type }}
  selector:
    app: n8n
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.n8n.port }}

